# Generated by Django 2.2.2 on 2019-11-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipcams',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('cam_ip', models.CharField(max_length=50)),
                ('cam_user', models.CharField(max_length=50)),
                ('cam_pass', models.CharField(max_length=50)),
                ('extension', models.IntegerField()),
            ],
            options={
                'db_table': 'ipcams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('locationid', models.AutoField(db_column='LocationID', primary_key=True, serialize=False)),
                ('locationname', models.CharField(db_column='LocationName', max_length=50)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Location_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationmediaContent',
            fields=[
                ('locationmediaid', models.AutoField(db_column='LocationMediaID', primary_key=True, serialize=False, unique=True)),
                ('locationid', models.IntegerField(blank=True, db_column='LocationID', null=True)),
                ('mediatype', models.CharField(blank=True, db_column='MediaType', max_length=50, null=True)),
                ('locationmediaurl', models.TextField(blank=True, db_column='LocationMediaUrl', null=True)),
            ],
            options={
                'db_table': 'LocationMedia_Content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'media_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaMaster',
            fields=[
                ('mediaid', models.AutoField(db_column='MediaID', primary_key=True, serialize=False)),
                ('mediatype', models.CharField(blank=True, db_column='MediaType', max_length=25, null=True)),
                ('mediaurl', models.TextField(blank=True, db_column='MediaUrl', null=True)),
                ('isactive', models.IntegerField(blank=True, db_column='IsActive', null=True)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('lastbrodcasteddate', models.DateTimeField(blank=True, db_column='LastBrodcastedDate', null=True)),
            ],
            options={
                'db_table': 'Media_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoStreamStatus',
            fields=[
                ('vss_id', models.AutoField(primary_key=True, serialize=False)),
                ('vss_extn_no', models.IntegerField()),
                ('vss_pid', models.IntegerField()),
                ('vss_status', models.CharField(max_length=50)),
                ('vss_stream_url', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'video_stream_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
