# Generated by Django 2.2.2 on 2019-11-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safemode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='cover',
            field=models.ImageField(upload_to='images1/'),
        ),
    ]
