# Generated by Django 2.2.2 on 2019-11-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safemode', '0003_auto_20191118_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebphoneUsers',
            fields=[
                ('wpid', models.AutoField(primary_key=True, serialize=False)),
                ('cam_id', models.IntegerField(blank=True, null=True)),
                ('wp_server_name', models.CharField(blank=True, max_length=50, null=True)),
                ('wp_user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('wp_user_password', models.CharField(blank=True, max_length=50, null=True)),
                ('wp_user_status', models.IntegerField(blank=True, null=True)),
                ('wp_user_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
