# Generated by Django 2.0.1 on 2019-09-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postimage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
